watch_stylesheet: true
watch_config: true
debug: false
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "bottom"
      center: false
    animation:
      enabled: true
      duration: 1000
    blur_effect:
      enabled: True
      acrylic: True
      dark_mode: True
      round_corners: True
      round_corners_type: "normal"
      border_color: "System"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: ["leftside-group"]
      center: []
      right:
        [
          "systray",
          "language",
          "rightside-group",
          "clock",
          "power_menu",
        ]
widgets:
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: false
      hide_if_offline: false
      btn_shadow:
        enabled: false
        color: "black"
        radius: 6
        offset: [1, 1]
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  leftside-group:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "leftside-group"
      widgets: ["glazewm_workspaces"]
  rightside-group:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "rightside-group"
      widgets: [
        "volume",
        "microphone",
        "update_check",
        "notifications"
    ]
  update_check:
    type: "yasb.update_check.UpdateCheckWidget"
    options:
      windows_update:
        enabled: false
        label: "<span>\uf407</span> {count}"
        interval: 240
        exclude: []
      winget_update:
        enabled: true
        label: "<span>\uf407</span> {count}"
        interval: 60
        exclude: []
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\udb80\udf5e"
      label_expanded: "\udb80\udf5f"
      label_position: "right"
      icon_size: 15
      pin_click_modifier: "alt"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a,%H:%M}"
      label_alt: "<span>\ue0c2</span>{%A %d %B %Y %H:%M}<span>\ue0c0</span>"
      timezones: []
      calendar:
        blur: true
        round_corners: true
        offset_top: 10
        offset_left: 200
        alignment: "center"
        direction: "up"
  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span> {level}"
      mute_text: "mute"
      icons:
        normal: "\uf130"
        muted: "\uf131"
      mic_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
      callbacks:
        on_left: "toggle_mic_menu"
        on_middle: "toggle_label"
        on_right: "toggle_mute"
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: "{count} notifications"
      hide_empty: false
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]
  language:
    type: "yasb.language.LanguageWidget"
    options:
      label: "<span>\uf1ab</span>{lang[country_code]}"
      label_alt: "{lang[native_lang_name]}"
      update_interval: 5
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      language_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "left"
        direction: "up"
        offset_top: 6
        offset_left: 0
        show_layout_icon: true
        layout_icon: "\uf11c"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"
        - "\uf028"
        - "\uf028"
        - "\uf028"
        - "\uf028"
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "left"
        direction: "up"
        offset_top: 6
        offset_left: 80
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [1, 1]
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: true
      blur: false
      blur_background: true
      animation_duration: 100
      button_row: 4
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
      label_shadow:
        enabled: false
        color: "black"
        radius: 6
        offset: [1, 1]
